server:
  applicationConnectors:
    - type: http
      port: 8000
  adminConnectors:
    - type: http
      port: 9000

logging:
  level: INFO
  appenders:
    - type: console

metrics:
  reporters:
    - type: graphite
      host: localhost
      port: 2003
      prefix: dropwizard-app
      durationUnit: milliseconds
      rateUnit: seconds
      frequency: 1 second
