# (min|max)ApplicationThreads = (min|max)Threads - selectorThreads- acceptorThreads
server:
  minThreads: 6
  maxThreads: 6
  applicationConnectors:
    - type: http
      port: 8000
      acceptorThreads: 1
      selectorThreads: 1
  adminMaxThreads: 3
  adminConnectors:
    - type: http
      port: 9000
      acceptorThreads: 1
      selectorThreads: 1

logging:
  level: INFO
  appenders:
    - type: console

metrics:
  reporters:
    - type: graphite
      host: localhost
      port: 2003
      prefix: dropwizard-app
      durationUnit: milliseconds
      rateUnit: seconds
      frequency: 1 second

httpClient:
  connectionRequestTimeout: 100ms
  connectionTimeout: 100ms
  timeout: 2000ms
  maxConnections: 20
  maxConnectionsPerRoute: 20
  retries: 0
