#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo "usage: $(basename $0) delay"
    echo ""
    echo "  delay :  dependency delay in milliseconds"
    exit 1
fi

DELAY=$1

if [ "$DELAY" -ge 0 ]; then
  curl -X POST --data "{\"fixedDelay\":${DELAY}}" http://localhost:8001/__admin/settings
  echo "Dependency has been dalyed by ${DELAY}ms"
else
  echo "Delay must be a positive value"
fi
